# Generated by Django 6.0.3 on 2026-07-09 11:19

import designdb.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature_family', models.TextField(blank=True, null=True)),
                ('feature_chain_name', models.TextField(blank=True, null=True)),
                ('feature_residue_name', models.TextField(blank=True, null=True)),
                ('feature_residue_number', models.IntegerField(blank=True, null=True)),
                ('feature_atom_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'features',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='InspirationModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inspirations',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='SubsiteModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subsite_name', models.TextField()),
                ('subsite_metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsites',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='CatalogueCompoundModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('catalogue_smiles', models.TextField(blank=True)),
                ('catalogue_inchikey', models.TextField(blank=True)),
                ('catalogue_hash', models.TextField(blank=True)),
                ('rdkit_version', models.TextField(blank=True, null=True)),
                ('inchi_version', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogue_compounds',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
                'constraints': [models.UniqueConstraint(fields=('catalogue_smiles',), name='uq_catalogue_compounds_smiles'), models.CheckConstraint(condition=models.Q(('catalogue_hash__isnull', False), ('catalogue_hash__gt', '')), name='ck_catalogue_compounds_hash_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='CataloguePriceModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor', models.TextField(blank=True)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('supplier_id', models.TextField(blank=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('purity', models.FloatField(blank=True, null=True)),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('catalogue_compound', models.ForeignKey(db_column='catalogue_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='designdb.cataloguecompoundmodel')),
            ],
            options={
                'db_table': 'catalogue_prices',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='CataloguePriceCompoundJunctionModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pk', models.CompositePrimaryKey('compound_id', 'catalogue_price_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('match_hash', models.TextField(blank=True)),
                ('catalogue_price', models.ForeignKey(db_column='catalogue_price_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.cataloguepricemodel')),
            ],
            options={
                'db_table': 'compound_catalogue_map',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='CompoundModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('compound_inchikey', models.TextField(blank=True, null=True)),
                ('compound_alias', models.TextField(blank=True, null=True)),
                ('compound_smiles', models.TextField(blank=True, null=True)),
                ('compound_hash', models.TextField(blank=True, default='a')),
                ('compound_mol', models.TextField(blank=True, null=True)),
                ('compound_pattern_bfp', models.BinaryField(max_length=2048, null=True)),
                ('compound_morgan_bfp', models.BinaryField(max_length=2048, null=True)),
                ('compound_metadata', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('rdkit_version', models.TextField(blank=True, null=True)),
                ('inchi_version', models.TextField(blank=True, null=True)),
                ('base_compound', models.ForeignKey(blank=True, db_column='base_compound_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='designdb.compoundmodel')),
            ],
            options={
                'db_table': 'compounds',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='CompoundEnumerationMethodJunctionModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pk', models.CompositePrimaryKey('compound_id', 'enumeration_method_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('compound', models.ForeignKey(db_column='compound_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.compoundmodel')),
            ],
            options={
                'db_table': 'has_enumeration_methods',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='cataloguepricemodel',
            name='compounds',
            field=models.ManyToManyField(related_name='prices', through='designdb.CataloguePriceCompoundJunctionModel', to='designdb.compoundmodel'),
        ),
        migrations.AddField(
            model_name='cataloguepricecompoundjunctionmodel',
            name='compound',
            field=models.ForeignKey(db_column='compound_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.compoundmodel'),
        ),
        migrations.CreateModel(
            name='CompoundTagModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('compound_tag_name', models.TextField()),
                ('compound_tag_description', models.TextField(blank=True, null=True)),
                ('compound_tag_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compound_tags',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
                'indexes': [models.Index(fields=['created_on'], name='idx_compound_tag_created')],
                'constraints': [models.UniqueConstraint(fields=('compound_tag_name',), name='uc_compound_tag_name')],
            },
        ),
        migrations.CreateModel(
            name='CompoundTagJunctionModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pk', models.CompositePrimaryKey('compound_id', 'compound_tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('compound', models.ForeignKey(db_column='compound_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.compoundmodel')),
                ('compound_tag', models.ForeignKey(db_column='compound_tag_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.compoundtagmodel')),
            ],
            options={
                'db_table': 'has_compound_tags',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='compoundmodel',
            name='tags',
            field=models.ManyToManyField(related_name='compounds', through='designdb.CompoundTagJunctionModel', to='designdb.compoundtagmodel'),
        ),
        migrations.CreateModel(
            name='EnumerationMethodModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enum_name', models.TextField(blank=True, null=True)),
                ('enum_description', models.TextField(blank=True, null=True)),
                ('enum_version', models.TextField(blank=True, null=True)),
                ('enum_organization', models.TextField(blank=True, null=True)),
                ('enum_link', models.TextField(blank=True, null=True)),
                ('enum_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enumeration_methods',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
                'indexes': [models.Index(fields=['enum_name'], name='idx_enumeration_method_name'), models.Index(fields=['created_on'], name='idx_enumeration_method_created')],
                'constraints': [models.UniqueConstraint(fields=('enum_name', 'enum_version'), name='uc_enumeration_method', nulls_distinct=False)],
            },
        ),
        migrations.AddField(
            model_name='compoundmodel',
            name='enumeration_methods',
            field=models.ManyToManyField(related_name='compounds', through='designdb.CompoundEnumerationMethodJunctionModel', to='designdb.enumerationmethodmodel'),
        ),
        migrations.AddField(
            model_name='compoundenumerationmethodjunctionmodel',
            name='enumeration_method',
            field=models.ForeignKey(db_column='enumeration_method_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.enumerationmethodmodel'),
        ),
        migrations.CreateModel(
            name='PoseMethodModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pose_method_name', models.TextField(blank=True, null=True)),
                ('pose_method_description', models.TextField(blank=True, null=True)),
                ('pose_method_version', models.TextField(blank=True, null=True)),
                ('pose_method_organization', models.TextField(blank=True, null=True)),
                ('pose_method_link', models.TextField(blank=True, null=True)),
                ('pose_method_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pose_methods',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
                'indexes': [models.Index(fields=['pose_method_name'], name='idx_pose_method_name'), models.Index(fields=['created_on'], name='idx_pose_method_created')],
                'constraints': [models.UniqueConstraint(fields=('pose_method_name', 'pose_method_version'), name='uc_pose_method', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='PoseMethodJunctionModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pk', models.CompositePrimaryKey('pose_id', 'pose_method_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pose_method', models.ForeignKey(db_column='pose_method_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.posemethodmodel')),
            ],
            options={
                'db_table': 'has_pose_methods',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='PoseModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pose_inchikey', models.TextField(blank=True, null=True)),
                ('pose_alias', models.TextField(blank=True, null=True)),
                ('pose_smiles', models.TextField(blank=True, null=True)),
                ('pose_reference', models.IntegerField(blank=True, null=True)),
                ('protein_link', models.TextField(blank=True, null=True)),
                ('pose_mol', designdb.models.RDKitMolField(null=True)),
                ('pose_fingerprint', models.IntegerField(blank=True, null=True)),
                ('pose_metadata', designdb.models.JSONTextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('rdkit_version', models.TextField(blank=True, null=True)),
                ('inchi_version', models.TextField(blank=True, null=True)),
                ('compound', models.ForeignKey(db_column='compound_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.compoundmodel')),
                ('inspirations', models.ManyToManyField(through='designdb.InspirationModel', through_fields=('derivative_pose', 'original_pose'), to='designdb.posemodel')),
                ('methods', models.ManyToManyField(related_name='poses', through='designdb.PoseMethodJunctionModel', to='designdb.posemethodmodel')),
            ],
            options={
                'db_table': 'poses',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='posemethodjunctionmodel',
            name='pose',
            field=models.ForeignKey(db_column='pose_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.posemodel'),
        ),
        migrations.CreateModel(
            name='InteractionModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.TextField()),
                ('interaction_family', models.TextField()),
                ('interaction_atom_id', models.TextField()),
                ('interaction_prot_coord', models.TextField()),
                ('interaction_lig_coord', models.TextField()),
                ('interaction_distance', models.FloatField()),
                ('interaction_angle', models.FloatField(blank=True, null=True)),
                ('interaction_energy', models.FloatField(blank=True, null=True)),
                ('feature', models.ForeignKey(db_column='feature_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.featuremodel')),
                ('pose', models.ForeignKey(db_column='pose_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.posemodel')),
            ],
            options={
                'db_table': 'interactions',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='inspirationmodel',
            name='derivative_pose',
            field=models.ForeignKey(db_column='derivative_pose_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='designdb.posemodel'),
        ),
        migrations.AddField(
            model_name='inspirationmodel',
            name='original_pose',
            field=models.ForeignKey(db_column='original_pose_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='designdb.posemodel'),
        ),
        migrations.CreateModel(
            name='PoseTagModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pose_tag_name', models.TextField()),
                ('pose_tag_description', models.TextField(blank=True, null=True)),
                ('pose_tag_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pose_tags',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
                'indexes': [models.Index(fields=['created_on'], name='idx_pose_tag_created')],
                'constraints': [models.UniqueConstraint(fields=('pose_tag_name',), name='uc_pose_tag')],
            },
        ),
        migrations.CreateModel(
            name='PoseTagJunctionModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pk', models.CompositePrimaryKey('pose_id', 'pose_tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pose', models.ForeignKey(db_column='pose_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.posemodel')),
                ('pose_tag', models.ForeignKey(db_column='pose_tag_id', on_delete=django.db.models.deletion.CASCADE, to='designdb.posetagmodel')),
            ],
            options={
                'db_table': 'has_pose_tags',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='posemodel',
            name='tags',
            field=models.ManyToManyField(related_name='poses', through='designdb.PoseTagJunctionModel', to='designdb.posetagmodel'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('project_name', models.TextField(unique=True)),
                ('open_to_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
                'constraints': [models.UniqueConstraint(fields=('project_name',), name='uc_project')],
            },
        ),
        migrations.CreateModel(
            name='ReactionModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reaction_type', models.TextField(blank=True, null=True)),
                ('reaction_product_yield', models.FloatField(blank=True, null=True)),
                ('reaction_metadata', models.TextField(blank=True, null=True)),
                ('product_compound', models.ForeignKey(db_column='product_compound_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.compoundmodel')),
            ],
            options={
                'db_table': 'reactions',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='ReactantModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reactant_amount', models.FloatField(blank=True, null=True)),
                ('compound', models.ForeignKey(db_column='compound_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.compoundmodel')),
                ('reaction', models.ForeignKey(db_column='reaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactants', to='designdb.reactionmodel')),
            ],
            options={
                'db_table': 'reactants',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_compound', models.ForeignKey(db_column='product_compound_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.compoundmodel')),
            ],
            options={
                'db_table': 'routes',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('component_type', models.IntegerField(blank=True, null=True)),
                ('component_ref', models.IntegerField(blank=True, null=True)),
                ('component_amount', models.FloatField(blank=True, null=True)),
                ('route', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.routemodel')),
            ],
            options={
                'db_table': 'components',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='ScaffoldModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_compound', models.ForeignKey(db_column='base_compound_id', on_delete=django.db.models.deletion.CASCADE, related_name='scaffold_bases', to='designdb.compoundmodel')),
                ('superstructure_compound', models.ForeignKey(db_column='superstructure_compound_id', on_delete=django.db.models.deletion.CASCADE, related_name='scaffold_superstructures', to='designdb.compoundmodel')),
            ],
            options={
                'db_table': 'scaffolds',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='compoundmodel',
            name='scaffolds',
            field=models.ManyToManyField(through='designdb.ScaffoldModel', to='designdb.compoundmodel'),
        ),
        migrations.CreateModel(
            name='ScoringMethodModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method_name', models.TextField(blank=True, null=True)),
                ('method_description', models.TextField(blank=True, null=True)),
                ('method_version', models.TextField(blank=True, null=True)),
                ('method_organization', models.TextField(blank=True, null=True)),
                ('method_link', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scoring_methods',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
                'indexes': [models.Index(fields=['method_name'], name='idx_scoring_method_name'), models.Index(fields=['created_on'], name='idx_scoring_method_created')],
                'constraints': [models.UniqueConstraint(fields=('method_name', 'method_version'), name='uc_scoring_method', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='ScoreValueModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pk', models.CompositePrimaryKey('pose_id', 'compound_id', 'scoring_method_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('score', models.JSONField()),
                ('compound', models.ForeignKey(db_column='compound_id', on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='designdb.compoundmodel')),
                ('pose', models.ForeignKey(db_column='pose_id', on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='designdb.posemodel')),
                ('scoring_method', models.ForeignKey(db_column='scoring_method_id', on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='designdb.scoringmethodmodel')),
            ],
            options={
                'db_table': 'score_values',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='SubsiteTagModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subsite_tag_metadata', models.TextField(blank=True, null=True)),
                ('pose', models.ForeignKey(db_column='pose_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.posemodel')),
                ('subsite', models.ForeignKey(db_column='subsite_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.subsitemodel')),
            ],
            options={
                'db_table': 'subsite_tags',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='posemodel',
            name='subsites',
            field=models.ManyToManyField(through='designdb.SubsiteTagModel', to='designdb.subsitemodel'),
        ),
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_target_id', models.BigIntegerField(blank=True, null=True)),
                ('target_name', models.TextField()),
                ('target_metadata', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.project')),
            ],
            options={
                'db_table': 'targets',
                'abstract': False,
                'managed': True,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddField(
            model_name='subsitemodel',
            name='target',
            field=models.ForeignKey(db_column='target_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.targetmodel'),
        ),
        migrations.AddField(
            model_name='posemodel',
            name='target',
            field=models.ForeignKey(db_column='target_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.targetmodel'),
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='target',
            field=models.ForeignKey(db_column='target_id', on_delete=django.db.models.deletion.RESTRICT, to='designdb.targetmodel'),
        ),
        migrations.AddConstraint(
            model_name='cataloguepricemodel',
            constraint=models.UniqueConstraint(fields=('catalogue_compound', 'vendor', 'supplier', 'supplier_id', 'amount'), name='uc_catalogue_price'),
        ),
        migrations.AddConstraint(
            model_name='cataloguepricecompoundjunctionmodel',
            constraint=models.CheckConstraint(condition=models.Q(('match_hash__isnull', False), ('match_hash__gt', '')), name='ck_compound_catalogue_map_match_hash_nonempty'),
        ),
        migrations.AddIndex(
            model_name='compoundtagjunctionmodel',
            index=models.Index(fields=['compound_tag'], name='idx_has_compound_tag_compound_tag_id'),
        ),
        migrations.AddIndex(
            model_name='compoundtagjunctionmodel',
            index=models.Index(fields=['created_on'], name='idx_has_compound_tag_created'),
        ),
        migrations.AddIndex(
            model_name='compoundenumerationmethodjunctionmodel',
            index=models.Index(fields=['enumeration_method'], name='idx_has_enumeration_methods_enumeration_method_id'),
        ),
        migrations.AddIndex(
            model_name='compoundenumerationmethodjunctionmodel',
            index=models.Index(fields=['created_on'], name='idx_has_enumeration_methods_created'),
        ),
        migrations.AddIndex(
            model_name='posemethodjunctionmodel',
            index=models.Index(fields=['pose_method'], name='idx_has_pose_methods_pose_method_id'),
        ),
        migrations.AddIndex(
            model_name='posemethodjunctionmodel',
            index=models.Index(fields=['created_on'], name='idx_idx_has_pose_methods_created'),
        ),
        migrations.AddIndex(
            model_name='interactionmodel',
            index=models.Index(fields=['feature_id'], name='idx_interaction_feature_id'),
        ),
        migrations.AddIndex(
            model_name='interactionmodel',
            index=models.Index(fields=['pose'], name='idx_interaction_pose_id'),
        ),
        migrations.AddIndex(
            model_name='interactionmodel',
            index=models.Index(fields=['created_on'], name='idx_interaction_created'),
        ),
        migrations.AddConstraint(
            model_name='interactionmodel',
            constraint=models.UniqueConstraint(fields=('feature', 'pose', 'interaction_type', 'interaction_family', 'interaction_atom_id'), name='uc_interaction'),
        ),
        migrations.AddIndex(
            model_name='inspirationmodel',
            index=models.Index(fields=['original_pose'], name='idx_inspiration_original_pose_id'),
        ),
        migrations.AddIndex(
            model_name='inspirationmodel',
            index=models.Index(fields=['derivative_pose'], name='idx_inspiration_derivative_pose_id'),
        ),
        migrations.AddIndex(
            model_name='inspirationmodel',
            index=models.Index(fields=['created_on'], name='idx_inspiration_created'),
        ),
        migrations.AddConstraint(
            model_name='inspirationmodel',
            constraint=models.UniqueConstraint(fields=('original_pose', 'derivative_pose'), name='uc_inspiration'),
        ),
        migrations.AddIndex(
            model_name='posetagjunctionmodel',
            index=models.Index(fields=['pose_tag'], name='idx_has_pose_tag_pose_tag_id'),
        ),
        migrations.AddIndex(
            model_name='posetagjunctionmodel',
            index=models.Index(fields=['created_on'], name='idx_has_pose_tag_created'),
        ),
        migrations.AddIndex(
            model_name='reactionmodel',
            index=models.Index(fields=['product_compound'], name='idx_reaction_product_compound_id'),
        ),
        migrations.AddIndex(
            model_name='reactionmodel',
            index=models.Index(fields=['created_on'], name='idx_reaction_created'),
        ),
        migrations.AddIndex(
            model_name='reactantmodel',
            index=models.Index(fields=['reaction'], name='idx_reactant_reaction_id'),
        ),
        migrations.AddIndex(
            model_name='reactantmodel',
            index=models.Index(fields=['compound'], name='idx_reactant_compound_id'),
        ),
        migrations.AddIndex(
            model_name='reactantmodel',
            index=models.Index(fields=['created_on'], name='idx_reactant_created'),
        ),
        migrations.AddConstraint(
            model_name='reactantmodel',
            constraint=models.UniqueConstraint(fields=('reaction', 'compound'), name='uc_reactant'),
        ),
        migrations.AddIndex(
            model_name='routemodel',
            index=models.Index(fields=['product_compound'], name='idx_route_product_compound_id'),
        ),
        migrations.AddIndex(
            model_name='routemodel',
            index=models.Index(fields=['created_on'], name='idx_route_created'),
        ),
        migrations.AddIndex(
            model_name='componentmodel',
            index=models.Index(fields=['route'], name='idx_component_route_id'),
        ),
        migrations.AddIndex(
            model_name='componentmodel',
            index=models.Index(fields=['created_on'], name='idx_component_created'),
        ),
        migrations.AddConstraint(
            model_name='componentmodel',
            constraint=models.UniqueConstraint(fields=('route', 'component_ref', 'component_type'), name='uc_component'),
        ),
        migrations.AddIndex(
            model_name='scaffoldmodel',
            index=models.Index(fields=['base_compound'], name='idx_scaffold_base_compound_id'),
        ),
        migrations.AddIndex(
            model_name='scaffoldmodel',
            index=models.Index(fields=['superstructure_compound'], name='idx_scaffold_superstructure_compound_id'),
        ),
        migrations.AddIndex(
            model_name='scaffoldmodel',
            index=models.Index(fields=['created_on'], name='idx_scaffold_created'),
        ),
        migrations.AddConstraint(
            model_name='scaffoldmodel',
            constraint=models.UniqueConstraint(fields=('base_compound', 'superstructure_compound'), name='uc_scaffold'),
        ),
        migrations.AddIndex(
            model_name='compoundmodel',
            index=models.Index(fields=['compound_inchikey'], name='idx_compound_inchikey'),
        ),
        migrations.AddIndex(
            model_name='compoundmodel',
            index=models.Index(fields=['created_on'], name='idx_compound_created'),
        ),
        migrations.AddConstraint(
            model_name='compoundmodel',
            constraint=models.UniqueConstraint(fields=('compound_inchikey',), name='uc_compound_inchikey'),
        ),
        migrations.AddIndex(
            model_name='scorevaluemodel',
            index=models.Index(fields=['pose'], name='idx_score_values_pose_id'),
        ),
        migrations.AddIndex(
            model_name='scorevaluemodel',
            index=models.Index(fields=['compound'], name='idx_score_values_compound_id'),
        ),
        migrations.AddIndex(
            model_name='scorevaluemodel',
            index=models.Index(fields=['scoring_method'], name='idx_score_values_scoring_method_id'),
        ),
        migrations.AddIndex(
            model_name='scorevaluemodel',
            index=models.Index(fields=['created_on'], name='idx_score_values_created'),
        ),
        migrations.AddIndex(
            model_name='subsitetagmodel',
            index=models.Index(fields=['subsite'], name='idx_subsite_tag_subsite_id'),
        ),
        migrations.AddIndex(
            model_name='subsitetagmodel',
            index=models.Index(fields=['pose'], name='idx_subsite_tag_pose_id'),
        ),
        migrations.AddIndex(
            model_name='subsitetagmodel',
            index=models.Index(fields=['created_on'], name='idx_subsite_tag_created'),
        ),
        migrations.AddConstraint(
            model_name='subsitetagmodel',
            constraint=models.UniqueConstraint(fields=('subsite', 'pose'), name='uc_subsite_tag'),
        ),
        migrations.AddIndex(
            model_name='targetmodel',
            index=models.Index(fields=['target_name'], name='idx_target_name'),
        ),
        migrations.AddIndex(
            model_name='targetmodel',
            index=models.Index(fields=['created_on'], name='idx_target_created'),
        ),
        migrations.AddConstraint(
            model_name='targetmodel',
            constraint=models.UniqueConstraint(fields=('target_name',), name='uc_target'),
        ),
        migrations.AddIndex(
            model_name='subsitemodel',
            index=models.Index(fields=['target'], name='idx_subsite_target_id'),
        ),
        migrations.AddIndex(
            model_name='subsitemodel',
            index=models.Index(fields=['created_on'], name='idx_subsite_created'),
        ),
        migrations.AddConstraint(
            model_name='subsitemodel',
            constraint=models.UniqueConstraint(fields=('target', 'subsite_name'), name='uc_subsite'),
        ),
        migrations.AddIndex(
            model_name='posemodel',
            index=models.Index(fields=['compound'], name='idx_pose_compound_id'),
        ),
        migrations.AddIndex(
            model_name='posemodel',
            index=models.Index(fields=['target'], name='idx_pose_target_id'),
        ),
        migrations.AddIndex(
            model_name='posemodel',
            index=models.Index(fields=['protein_link'], name='idx_protein_link'),
        ),
        migrations.AddIndex(
            model_name='posemodel',
            index=models.Index(fields=['created_on'], name='idx_pose_created'),
        ),
        migrations.AddIndex(
            model_name='featuremodel',
            index=models.Index(fields=['target'], name='idx_feature_target_id'),
        ),
        migrations.AddIndex(
            model_name='featuremodel',
            index=models.Index(fields=['created_on'], name='idx_feature_created'),
        ),
        migrations.AddConstraint(
            model_name='featuremodel',
            constraint=models.UniqueConstraint(fields=('feature_family', 'target', 'feature_chain_name', 'feature_residue_name', 'feature_residue_number', 'feature_atom_name'), name='uc_feature'),
        ),
    ]
